ALTER TABLE "equipment_brands"
ADD COLUMN IF NOT EXISTS "standby_kw" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "running_kw" DECIMAL(65,30) NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "area_target" "AreaTarget" NOT NULL DEFAULT 'SALES';
